---
apiVersion: v1
kind: Pod
metadata: 
    name: mynginx
    labels:
            Myapp: firstpod
spec:
    containers:
        - image: nginx
          name: mynignx
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
    name: myapache
    labels:
            Myapp: secondpod
spec:
    containers:
        - image: httpd
          name: apache
          ports:
            - containerPort: 80
              protocol: TCP

